# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/cpu_vivado2019/opentitan/opentitan.cache/wt [current_project]
set_property parent.project_path D:/cpu_vivado2019/opentitan/opentitan.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/cpu_vivado2019/opentitan/opentitan.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_assert.h
set_property file_type "Verilog Header" [get_files D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_assert.h]
set_property is_global_include true [get_files D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_assert.h]
read_verilog -library xil_defaultlib -sv {
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/top_earlgrey/rtl/top_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/tlul/rtl/tlul_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/aes/rtl/aes_reg_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/aes/rtl/aes.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/aes/rtl/aes_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/aes/rtl/aes_control.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/aes/rtl/aes_core.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/aes/rtl/aes_key_expand.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/aes/rtl/aes_mix_columns.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/aes/rtl/aes_mix_single_column.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/aes/rtl/aes_reg_top.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/aes/rtl/aes_sbox_lut.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/aes/rtl/aes_shift_rows.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/aes/rtl/aes_sub_bytes.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/examples/fpga/artya7-100/rtl/clkgen_xil7series.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/pulp_riscv_dbg/debug_rom/debug_rom.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/pulp_riscv_dbg/src/dm_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/pulp_riscv_dbg/src/dm_csrs.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/pulp_riscv_dbg/src/dm_mem.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/pulp_riscv_dbg/src/dm_sba.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/pulp_riscv_dbg/src/dmi_cdc.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/pulp_riscv_dbg/src/dmi_jtag.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/pulp_riscv_dbg/src/dmi_jtag_tap.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/flash_ctrl/rtl/flash_ctrl_reg_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/flash_ctrl/rtl/flash_ctrl.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/flash_ctrl/rtl/flash_ctrl_reg_top.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/flash_ctrl/rtl/flash_erase_ctrl.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/flash_ctrl/rtl/flash_mp.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/flash_ctrl/rtl/flash_phy.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/flash_ctrl/rtl/flash_prog_ctrl.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/flash_ctrl/rtl/flash_rd_ctrl.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/gpio/rtl/gpio_reg_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/gpio/rtl/gpio.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/gpio/rtl/gpio_reg_top.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/hmac/rtl/hmac_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/hmac/rtl/hmac_reg_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/hmac/rtl/hmac.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/hmac/rtl/hmac_core.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/hmac/rtl/hmac_reg_top.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_alu.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_compressed_decoder.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_controller.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_core.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_cs_registers.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_decoder.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_ex_block.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_fetch_fifo.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_id_stage.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_if_stage.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_load_store_unit.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_multdiv_fast.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_multdiv_slow.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_pmp.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_prefetch_buffer.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/rtl/ibex_register_file_latch.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/top_earlgrey/rtl/padctl.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/top_earlgrey/ip/pinmux/rtl/autogen/pinmux_reg_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/pinmux/rtl/pinmux.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/top_earlgrey/ip/pinmux/rtl/autogen/pinmux_reg_top.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_arbiter.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/vendor/lowrisc_ibex/examples/fpga/artya7-100/rtl/prim_clock_gating.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_clock_inverter.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/abstract/prim_clock_mux2.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_fifo_async.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_fifo_sync.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_filter_ctr.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/abstract/prim_flash.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_flop_2sync.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim_generic/rtl/prim_generic_clock_mux2.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim_generic/rtl/prim_generic_flash.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim_generic/rtl/prim_generic_ram_1p.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim_generic/rtl/prim_generic_ram_2p.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim_generic/rtl/prim_generic_rom.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_intr_hw.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_packer.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_pulse_sync.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/abstract/prim_ram_1p.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/abstract/prim_ram_2p.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_ram_2p_adv.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/abstract/prim_rom.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_secded_39_32_dec.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_secded_39_32_enc.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_sram_arbiter.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_subreg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim/rtl/prim_subreg_ext.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim_xilinx/rtl/prim_xilinx_clock_mux2.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim_xilinx/rtl/prim_xilinx_ram_2p.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/prim_xilinx/rtl/prim_xilinx_rom.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/rv_core_ibex/rtl/rv_core_ibex.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/rv_dm/rtl/rv_dm.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/top_earlgrey/ip/rv_plic/rtl/autogen/rv_plic_reg_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/top_earlgrey/ip/rv_plic/rtl/autogen/rv_plic.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/rv_plic/rtl/rv_plic_gateway.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/top_earlgrey/ip/rv_plic/rtl/autogen/rv_plic_reg_top.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/rv_plic/rtl/rv_plic_target.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/rv_timer/rtl/rv_timer_reg_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/rv_timer/rtl/rv_timer.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/rv_timer/rtl/rv_timer_reg_top.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/hmac/rtl/sha2.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/hmac/rtl/sha2_pad.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/spi_device/rtl/spi_device_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/spi_device/rtl/spi_device_reg_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/spi_device/rtl/spi_device.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/spi_device/rtl/spi_device_reg_top.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/spi_device/rtl/spi_fwm_rxf_ctrl.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/spi_device/rtl/spi_fwm_txf_ctrl.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/spi_device/rtl/spi_fwmode.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/rv_timer/rtl/timer_core.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/top_earlgrey/ip/xbar/rtl/autogen/tl_main_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/rv_dm/rtl/tlul_adapter_host.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/tlul/rtl/tlul_adapter_reg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/tlul/rtl/tlul_adapter_sram.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/tlul/rtl/tlul_err.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/tlul/rtl/tlul_err_resp.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/tlul/rtl/tlul_fifo_sync.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/tlul/rtl/tlul_socket_1n.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/tlul/rtl/tlul_socket_m1.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/uart/rtl/uart_reg_pkg.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/uart/rtl/uart.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/uart/rtl/uart_core.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/uart/rtl/uart_reg_top.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/uart/rtl/uart_rx.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/ip/uart/rtl/uart_tx.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/top_earlgrey/ip/xbar/rtl/autogen/xbar_main.sv
  D:/cpu_vivado2019/opentitan/opentitan.srcs/sources_1/imports/hw/top_earlgrey/rtl/top_earlgrey_artys7.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_earlgrey_artys7 -part xc7a100tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_earlgrey_artys7.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_earlgrey_artys7_utilization_synth.rpt -pb top_earlgrey_artys7_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
